spring.application.name=todoApplication 
server.port=8090

server.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/todoApp
spring.datasource.username=postgres
spring.datasource.password=PSQL1234
spring.jpa.show-sql=true

jwt-secret="C6UlILsE6GJwNqwCTkkvJj9O653yJUoteWMLfYyrc3vaGrrTOrJFAUD1wEBnnposzcQl"
jwt-expiration-ms=86400000